=== otuncelli/PaintDotNet.IndirectUI.Fluent/PaintDotNet.IndirectUI.Fluent/PaintDotNet/IndirectUI/Xml/Schema/IndirectUI.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="qualified" elementFormDefault="qualified"
		   xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:simpleType name="ValidationFailureResult">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Ignore" />
            <xs:enumeration value="Clamp" />
            <xs:enumeration value="ThrowException" />
        </xs:restriction>
    </xs:simpleType>
	<xs:simpleType name="ColorHexCode">
		<xs:union memberTypes="xs:NMTOKEN">
			<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:pattern value="#[\da-fA-F]{6}([\da-fA-F]{2})?"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:union>
	</xs:simpleType>
    <xs:complexType name="ControlColors">
        <xs:sequence minOccurs="3" maxOccurs="3">
            <xs:element name="Color" type="ColorHexCode" default="#FFFFFF" />
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="SliderControlStyle">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Default" />
            <xs:enumeration value="Hue" />
            <xs:enumeration value="HueCentered" />
            <xs:enumeration value="SaturationHue" />
        </xs:restriction>        
    </xs:simpleType>
	<xs:complexType name="ReadOnlyBoundToBoolean">
		<xs:attribute name="SourceControl" use="required" type="xs:string" />
		<xs:attribute name="Inverse" type="xs:boolean" />
	</xs:complexType>
	<xs:complexType name="ReadOnlyBoundToValues">
		<xs:attribute name="SourceControl" use="required" type="xs:string" />
		<xs:attribute name="CommaSeparatedValues" use="required" type="xs:string" />
		<xs:attribute name="Inverse" type="xs:boolean" />
	</xs:complexType>
	<xs:complexType name="ReadOnlyBoundToNameValues1">
		<xs:attribute name="TargetControl" use="required" type="xs:string" />
		<xs:attribute name="SourceControl" use="required" type="xs:string" />
		<xs:attribute name="Value" use="required" type="xs:string" />
	</xs:complexType>
	<xs:complexType name="ReadOnlyBoundToNameValues">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="Pair" type="ReadOnlyBoundToNameValues1" />
		</xs:sequence>
		<xs:attribute name="Inverse" type="xs:boolean" />
	</xs:complexType>
	<xs:complexType name="BaseControl">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="BoundToBoolean" minOccurs="0" maxOccurs="unbounded" type="ReadOnlyBoundToBoolean" />
			<xs:element name="BoundToValues" minOccurs="0" maxOccurs="unbounded" type="ReadOnlyBoundToValues" />
			<xs:element name="BoundToNameValues" minOccurs="0" maxOccurs="unbounded" type="ReadOnlyBoundToNameValues" />
		</xs:sequence>
		<xs:attribute name="Name" use="required" type="xs:ID" />
		<xs:attribute name="ReadOnly" type="xs:boolean" default="false" />
		<xs:attribute name="OnValidationFailure" type="ValidationFailureResult" default="Clamp"></xs:attribute>
		<xs:attribute name="Description" type="xs:string" default="" />
		<xs:attribute name="DisplayName" type="xs:string" />
	</xs:complexType>
	<xs:complexType name="BaseSlider">
		<xs:complexContent>
			<xs:extension base="BaseControl">
				<xs:sequence>
					<xs:element name="ControlColors" type="ControlColors" minOccurs="0" maxOccurs="1" />
				</xs:sequence>
				<xs:attribute name="ControlStyle" type="SliderControlStyle" default="Default" />
				<xs:attribute name="RangeWraps" type="xs:boolean" />
				<xs:attribute name="ShowResetButton" type="xs:boolean" default="true" />
				<xs:attribute name="SliderLargeChange" type="xs:double" default="5" />
				<xs:attribute name="SliderSmallChange" type="xs:double" default="1" />
				<xs:attribute name="UpDownIncrement" type="xs:double" default="1" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
    <!-- ::Int32Property:: -->
    <xs:complexType name="IntSlider">
		<xs:complexContent>
			<xs:extension base="BaseSlider">
				<xs:attribute name="Value" type="xs:int" />
				<xs:attribute name="MinValue" type="xs:int" default="-2147483648" />
				<xs:attribute name="MaxValue" type="xs:int" default="2147483647" />
				<xs:attribute name="SliderShowTickMarks" type="xs:boolean" />
			</xs:extension>
		</xs:complexContent>
    </xs:complexType>
    <xs:complexType name="ColorWheel">
		<xs:complexContent>
			<xs:extension base="BaseControl">
				<xs:attribute name="Value" type="ColorHexCode" default="#00000000" />
				<xs:attribute name="MinValue" type="xs:int" default="-2147483648" />
				<xs:attribute name="MaxValue" type="xs:int" default="2147483647" />
				<xs:attribute name="Alpha" type="xs:boolean" default="true" />
				<xs:attribute name="ShowResetButton" type="xs:boolean" default="true" />
			</xs:extension>
		</xs:complexContent>
    </xs:complexType>
    <xs:complexType name="IncrementButton">
		<xs:complexContent>
			<xs:extension base="BaseControl">
				<xs:attribute name="Value" type="xs:int" />
				<xs:attribute name="MinValue" type="xs:int" default="-2147483648" />
				<xs:attribute name="MaxValue" type="xs:int" default="2147483647" />
				<xs:attribute name="ButtonText" type="xs:string" default="+" />
			</xs:extension>
		</xs:complexContent>
    </xs:complexType>
    <!-- ==Int32Property== -->    
    <!-- ::DoubleProperty:: -->
    <xs:complexType name="DoubleSlider">
		<xs:complexContent>
			<xs:extension base="BaseSlider">
				<xs:attribute name="Value" type="xs:double" />
				<xs:attribute name="MinValue" type="xs:double" default="-32768" />
				<xs:attribute name="MaxValue" type="xs:double" default="32767" />
				<xs:attribute name="DecimalPlaces" type="xs:int" default="2" />
				<xs:attribute name="UseExponentialScale" type="xs:boolean" />
			</xs:extension>
		</xs:complexContent>
    </xs:complexType>
    <xs:simpleType name="AngleMin">
        <xs:restriction base="xs:double">
            <xs:enumeration value="-180"></xs:enumeration>
            <xs:enumeration value="0"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="AngleMax">
        <xs:restriction base="xs:double">
            <xs:enumeration value="180"></xs:enumeration>
            <xs:enumeration value="360"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="Angle">
        <xs:restriction base="xs:double">
            <xs:minInclusive value="-180" />
            <xs:maxInclusive value="360" />
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="AngleChooser">
		<xs:complexContent>
			<xs:extension base="BaseControl">
				<xs:attribute name="Value" type="Angle" />
				<xs:attribute name="MinValue" type="AngleMin" default="0" />
				<xs:attribute name="MaxValue" type="AngleMax" default="360" />
				<xs:attribute name="UpDownIncrement" type="xs:double" default="1" />
				<xs:attribute name="ShowResetButton" type="xs:boolean" default="true" />
			</xs:extension>
		</xs:complexContent>
    </xs:complexType>
    <!-- ==DoubleProperty== -->
    <!-- ::BooleanProperty:: -->
    <xs:complexType name="CheckBox">
		<xs:complexContent>
			<xs:extension base="BaseControl">
				<xs:attribute name="Value" type="xs:boolean" />
				<xs:attribute name="Footnote" type="xs:string" default="" />
			</xs:extension>
		</xs:complexContent>
    </xs:complexType>
    <!-- ==BooleanProperty== -->
    <!-- ::DoubleVectorProperty:: -->
    <xs:attributeGroup name="CommonDoubleVector23">
        <xs:attribute name="xValue" type="xs:double" />
        <xs:attribute name="xMinValue" type="xs:double" default="-32767" />
        <xs:attribute name="xMaxValue" type="xs:double" default="32767" />
        <xs:attribute name="yValue" type="xs:double" />
        <xs:attribute name="yMinValue" type="xs:double" default="-32767" />
        <xs:attribute name="yMaxValue" type="xs:double" default="32767" />
        <xs:attribute name="ShowResetButton" type="xs:boolean" default="false" />
        <xs:attribute name="SliderLargeChangeX" type="xs:double" />
        <xs:attribute name="SliderLargeChangeY" type="xs:double" />
        <xs:attribute name="SliderShowTickMarksX" type="xs:boolean" />
        <xs:attribute name="SliderShowTickMarksY" type="xs:boolean" />
        <xs:attribute name="SliderSmallChangeX" type="xs:double" />
        <xs:attribute name="SliderSmallChangeY" type="xs:double" />
        <xs:attribute name="UpDownIncrementX" type="xs:double" />
        <xs:attribute name="UpDownIncrementY" type="xs:double" />
    </xs:attributeGroup>    
    <xs:complexType name="DoubleVectorSlider">
		<xs:complexContent>
			<xs:extension base="BaseControl">
				<xs:attributeGroup ref="CommonDoubleVector23" />
				<xs:attribute name="DecimalPlaces" type="xs:int" default="2" />
				<xs:attribute name="UseExponentialScale" type="xs:boolean" />
			</xs:extension>
		</xs:complexContent>
    </xs:complexType>
    <xs:complexType name="DoubleVectorPanAndSlider">
		<xs:complexContent>
			<xs:extension base="BaseControl">
				<xs:attributeGroup ref="CommonDoubleVector23" />
				<xs:attribute name="StaticImageUnderlay" type="xs:base64Binary" />
			</xs:extension>
		</xs:complexContent>
    </xs:complexType>
    <!-- ==DoubleVectorProperty== -->
    <!-- ::DoubleVector3SliderProperty:: -->
    <xs:attributeGroup name="CommonDoubleVector3">
        <xs:attribute name="zValue" type="xs:double" />
        <xs:attribute name="zMinValue" type="xs:double" default="-32767" />
        <xs:attribute name="zMaxValue" type="xs:double" default="32767" />
        <xs:attribute name="SliderLargeChangeZ" type="xs:double" default="5" /> 
        <xs:attribute name="SliderShowTickMarksZ" type="xs:boolean" />
        <xs:attribute name="SliderSmallChangeZ" type="xs:double" default="1" />
        <xs:attribute name="UpDownIncrementZ" type="xs:double" default="1" />
    </xs:attributeGroup>    
    <xs:complexType name="DoubleVector3" abstract="true">
		<xs:complexContent>
			<xs:extension base="BaseControl">
				<xs:attributeGroup ref="CommonDoubleVector23" />
				<xs:attributeGroup ref="CommonDoubleVector3" />
			</xs:extension>
		</xs:complexContent>     
    </xs:complexType>
    <xs:complexType name="DoubleVector3Slider">
        <xs:complexContent>
            <xs:extension base="DoubleVector3" />
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="DoubleVector3RollBallAndSlider">
        <xs:complexContent>
            <xs:extension base="DoubleVector3" />
        </xs:complexContent>
    </xs:complexType>
    <!-- ==DoubleVector3SliderProperty== -->
    <!-- ::StringProperty:: -->
    <xs:complexType name="TextBox">
		<xs:complexContent>
			<xs:extension base="BaseControl">
				<xs:attribute name="Value" type="xs:string" default="" />
				<xs:attribute name="MaxLength" type="xs:int" default="32767" />
				<xs:attribute name="Multiline" type="xs:boolean" />
			</xs:extension>
		</xs:complexContent>
    </xs:complexType>
    <xs:complexType name="FileChooser">
		<xs:complexContent>
			<xs:extension base="BaseControl">
				<xs:attribute name="Path" type="xs:string" default="" />
				<xs:attribute name="AllowAllFiles" type="xs:boolean" />
				<xs:attribute name="FileTypes" type="xs:string" />
			</xs:extension>
		</xs:complexContent>  
    </xs:complexType>
    <xs:complexType name="FolderChooser">
		<xs:complexContent>
			<xs:extension base="BaseControl">
				<xs:attribute name="Path" type="xs:string" default="" />
			</xs:extension>
		</xs:complexContent>
    </xs:complexType>
    <!-- ==StringProperty== -->
    <!-- ::UriProperty:: -->
    <xs:complexType name="LinkLabel">
		<xs:complexContent>
			<xs:extension base="BaseControl">
				<xs:attribute name="Value" type="xs:anyURI" use="required" />
			</xs:extension>
		</xs:complexContent>
    </xs:complexType>
    <!-- ==UriProperty== -->
    <!-- ::StaticListChoice:: -->
	<xs:complexType name="ChoiceType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="Value" type="xs:ID" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	
    <xs:complexType name="StaticListChoice" abstract="true">
		<xs:complexContent>
			<xs:extension base="BaseControl">
				<xs:choice minOccurs="1" maxOccurs="unbounded">
					<xs:element name="Choice" type="ChoiceType" />
				</xs:choice>
			</xs:extension>
		</xs:complexContent>
    </xs:complexType>
    <xs:complexType name="DropDown">
        <xs:complexContent>
            <xs:extension base="StaticListChoice" />
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="RadioButton">
        <xs:complexContent>
            <xs:extension base="StaticListChoice" />
        </xs:complexContent>
    </xs:complexType>    
    <!-- ==StaticListChoice== -->
    <xs:complexType name="Controls">
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
			<xs:element name="AngleChooser" minOccurs="0" type="AngleChooser" />
            <xs:element name="CheckBox" minOccurs="0" type="CheckBox" />
            <xs:element name="ColorWheel" minOccurs="0" type="ColorWheel" />
            <xs:element name="DoubleSlider" minOccurs="0" type="DoubleSlider" />
            <xs:element name="DoubleVector3Slider" minOccurs="0" type="DoubleVector3Slider" />
            <xs:element name="DoubleVector3RollBallAndSlider" minOccurs="0" type="DoubleVector3RollBallAndSlider" />
            <xs:element name="DoubleVectorSlider" minOccurs="0" type="DoubleVectorSlider" />
            <xs:element name="DoubleVectorPanAndSlider" minOccurs="0" type="DoubleVectorPanAndSlider" />
            <xs:element name="DropDown" minOccurs="0" type="DropDown" />
            <xs:element name="FileChooser" minOccurs="0" type="FileChooser" />
            <xs:element name="FolderChooser" minOccurs="0" type="FolderChooser" />           
            <xs:element name="IncrementButton" minOccurs="0" type="IncrementButton" />
            <xs:element name="IntSlider" minOccurs="0" type="IntSlider" />
            <xs:element name="LinkLabel" minOccurs="0" type="LinkLabel" />
            <xs:element name="RadioButton" minOccurs="0" type="RadioButton" />
            <xs:element name="TextBox" minOccurs="0" type="TextBox" />
            <xs:element name="Container" minOccurs="0" type="Container"  />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="Panel">
        <xs:all>
            <xs:element name="Controls" minOccurs="0" maxOccurs="1" type="Controls" />
        </xs:all>
        <xs:attribute name="Name" type="xs:string" use="required" />
        <xs:attribute name="Text" type="xs:string" />
		<xs:attribute name="ToolTipText" type="xs:string" />
    </xs:complexType>
    <xs:complexType name="Container">
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="Panel" type="Panel" />
        </xs:sequence>
    </xs:complexType>
    <xs:element name="IndirectUI" type="Container" />
</xs:schema>

=== otuncelli/PaintDotNet.IndirectUI.Fluent/PaintDotNet.IndirectUI.Fluent/PaintDotNet/IndirectUI/Xml/IndirectUIDemo.xml
<?xml version="1.0" encoding="utf-8"?>
<IndirectUI xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Schema\IndirectUI.xsd">
	<Panel Name="First" Text="First Tab">
		<Controls>
			<AngleChooser Name="AngleChooser1" />
			<CheckBox Name="CheckBox1" 
					  DisplayName="Make ReadOnly 1" />
			<ColorWheel Name="ColorWheel1" 
						DisplayName="Test Color Wheel" 
						Value="#FFFF0000" 
						Alpha="true">
				<BoundToBoolean SourceControl="CheckBox1" />
			</ColorWheel>
			<IntSlider Name="IntSlider1"
                       DisplayName="Hello IntSlider"
                       MinValue="50"
                       MaxValue="100"
                       ShowResetButton="false">
				<BoundToBoolean SourceControl="CheckBox1" />
				<ControlColors>
					<Color>#FF0000</Color>
					<Color>#00FF00</Color>
					<Color>#0000FF</Color>
				</ControlColors>
			</IntSlider>
			<Container>
				<Panel Name="Nested First" 
					   Text="Nested First Tab">
					<Controls>
						<CheckBox Name="CheckBox2" 
								  DisplayName="Make ReadOnly 2" />
						<DoubleSlider Name="DoubleSlider1"
                                      DisplayName="Hello DoubleSlider1"
                                      MinValue="0"
                                      MaxValue="1"
                                      SliderSmallChange=".01"
                                      SliderLargeChange=".05"
                                      UpDownIncrement=".01"
                                      DecimalPlaces="2">
							<BoundToBoolean SourceControl="CheckBox2" />
						</DoubleSlider>
						<DoubleVector3RollBallAndSlider Name="RollBallAndSlider1">
							<BoundToBoolean SourceControl="CheckBox2" 
											Inverse="true" />
						</DoubleVector3RollBallAndSlider>
						<DoubleVector3Slider Name="Vector3Slider1">
							<BoundToBoolean SourceControl="CheckBox2" />
						</DoubleVector3Slider>
					</Controls>
				</Panel>
				<Panel Name="Nested Second" 
					   Text="Nested Second Tab">
					<Controls>
						<CheckBox Name="CheckBox3" 
								  DisplayName="Make ReadOnly 3" />
						<DoubleVectorPanAndSlider Name="PanAndSlider"
                                                  StaticImageUnderlay="iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAApgAAAKYB3X3/OAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAANCSURBVEiJtZZPbBtFFMZ/M7ubXdtdb1xSFyeilBapySVU8h8OoFaooFSqiihIVIpQBKci6KEg9Q6H9kovIHoCIVQJJCKE1ENFjnAgcaSGC6rEnxBwA04Tx43t2FnvDAfjkNibxgHxnWb2e/u992bee7tCa00YFsffekFY+nUzFtjW0LrvjRXrCDIAaPLlW0nHL0SsZtVoaF98mLrx3pdhOqLtYPHChahZcYYO7KvPFxvRl5XPp1sN3adWiD1ZAqD6XYK1b/dvE5IWryTt2udLFedwc1+9kLp+vbbpoDh+6TklxBeAi9TL0taeWpdmZzQDry0AcO+jQ12RyohqqoYoo8RDwJrU+qXkjWtfi8Xxt58BdQuwQs9qC/afLwCw8tnQbqYAPsgxE1S6F3EAIXux2oQFKm0ihMsOF71dHYx+f3NND68ghCu1YIoePPQN1pGRABkJ6Bus96CutRZMydTl+TvuiRW1m3n0eDl0vRPcEysqdXn+jsQPsrHMquGeXEaY4Yk4wxWcY5V/9scqOMOVUFthatyTy8QyqwZ+kDURKoMWxNKr2EeqVKcTNOajqKoBgOE28U4tdQl5p5bwCw7BWquaZSzAPlwjlithJtp3pTImSqQRrb2Z8PHGigD4RZuNX6JYj6wj7O4TFLbCO/Mn/m8R+h6rYSUb3ekokRY6f/YukArN979jcW+V/S8g0eT/N3VN3kTqWbQ428m9/8k0P/1aIhF36PccEl6EhOcAUCrXKZXXWS3XKd2vc/TRBG9O5ELC17MmWubD2nKhUKZa26Ba2+D3P+4/MNCFwg59oWVeYhkzgN/JDR8deKBoD7Y+ljEjGZ0sosXVTvbc6RHirr2reNy1OXd6pJsQ+gqjk8VWFYmHrwBzW/n+uMPFiRwHB2I7ih8ciHFxIkd/3Omk5tCDV1t+2nNu5sxxpDFNx+huNhVT3/zMDz8usXC3ddaHBj1GHj/As08fwTS7Kt1HBTmyN29vdwAw+/wbwLVOJ3uAD1wi/dUH7Qei66PfyuRj4Ik9is+hglfbkbfR3cnZm7chlUWLdwmprtCohX4HUtlOcQjLYCu+fzGJH2QRKvP3UNz8bWk1qMxjGTOMThZ3kvgLI5AzFfo379UAAAAASUVORK5CYII=">
							<BoundToBoolean SourceControl="CheckBox3" />
						</DoubleVectorPanAndSlider>
						<DropDown Name="DropDown1"
                                  DisplayName="Menü"
                                  Description="Description here...">
							<BoundToBoolean SourceControl="CheckBox3" />
							<Choice>Choice 1</Choice>
							<Choice>Choice 2</Choice>
							<Choice>Choice 3</Choice>
						</DropDown>
						<FileChooser Name="FileChooser1"
                                     AllowAllFiles="true">
						</FileChooser>
						<FolderChooser Name="FolderChooser1" />
					</Controls>
				</Panel>
			</Container>
		</Controls>
	</Panel>
	<Panel Name="Second" Text="Second Tab">
		<Controls>
			<CheckBox Name="CheckBox4" 
					  DisplayName="Make ReadOnly 4" />
			<IncrementButton Name="IncrementButton1" 
							 ButtonText="Click Me!">
				<BoundToBoolean SourceControl="CheckBox4" />
			</IncrementButton>
			<LinkLabel Name="LinkLabel1" 
					   DisplayName="Google" 
					   Value="http://www.google.com" />
			<RadioButton Name="RadioButton1" 
						 DisplayName="Radio Choice">
				<BoundToBoolean SourceControl="CheckBox4" />
				<Choice>Choice 1</Choice>
				<Choice>Choice 2</Choice>
				<Choice>Choice 3</Choice>
			</RadioButton>
		</Controls>
	</Panel>
</IndirectUI>
